const KEY="logisticsAccountV4Data";
const seed={users:[],accounts:[],transactions:[
{date:"2026-09-14",description:"Brian Motors - Sales invoice",debit:0,credit:8500,status:"Paid"},
{date:"2026-09-13",description:"Abba Suppliers - Office supplies",debit:3200,credit:0,status:"Pending"},
{date:"2026-09-12",description:"Road Agency - Transport expense",debit:1850,credit:0,status:"Paid"},
{date:"2026-09-11",description:"Felix Mwanza - Developer payment",debit:6000,credit:0,status:"Paid"}],journal:[],statements:[]};
const db=JSON.parse(localStorage.getItem(KEY)||JSON.stringify(seed));
let current={name:"Admin",username:"admin",role:"Admin"};
const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
function save(){localStorage.setItem(KEY,JSON.stringify(db))}
function money(n){return "K"+Number(n||0).toLocaleString("en-ZM",{minimumFractionDigits:0,maximumFractionDigits:2})}
function totals(){return db.transactions.reduce((x,t)=>({debit:x.debit+Number(t.debit||0),credit:x.credit+Number(t.credit||0)}),{debit:0,credit:0})}
function setHeader(title,sub){$("#pageTitle").textContent=title;$("#pageSubtitle").textContent=sub}
function dashboard(){
const t=totals(), rev=t.credit, exp=t.debit, profit=rev-exp;
setHeader("Dashboard","Overview of your accounting activity and financial performance.");
$("#pageContent").innerHTML=`<section class="stat-grid">
<article class="stat-card"><div class="stat-icon">↗</div><div class="stat-label">Total Revenue</div><div class="stat-value">${money(rev)}</div><div class="stat-change positive">Live <span>from recorded credits</span></div></article>
<article class="stat-card"><div class="stat-icon">↘</div><div class="stat-label">Total Expenses</div><div class="stat-value">${money(exp)}</div><div class="stat-change negative">Live <span>from recorded debits</span></div></article>
<article class="stat-card"><div class="stat-icon">▤</div><div class="stat-label">Net Profit</div><div class="stat-value">${money(profit)}</div><div class="stat-change ${profit>=0?"positive":"negative"}">${profit>=0?"Healthy":"Attention"} <span>revenue less expenses</span></div></article>
<article class="stat-card"><div class="stat-icon">◎</div><div class="stat-label">Cash Balance</div><div class="stat-value">${money(Math.max(0,profit))}</div><div class="stat-change positive">Calculated <span>current activity</span></div></article></section>
<section class="chart-grid"><article class="panel expense-panel"><div class="panel-head"><div><h2>All Expenses</h2><p>Expense distribution by category</p></div><select><option>This month</option><option>Last month</option><option>This year</option></select></div><div class="donut-wrap"><div class="donut"><div class="donut-center"><strong>100%</strong><span>Expenses</span></div></div><div class="legend"><div><b class="dot d1"></b> Operations <strong>28%</strong></div><div><b class="dot d2"></b> Payroll <strong>25%</strong></div><div><b class="dot d3"></b> Transport <strong>22%</strong></div><div><b class="dot d4"></b> Supplies <strong>15%</strong></div><div><b class="dot d5"></b> Other <strong>10%</strong></div></div></div></article>
<article class="panel earnings-panel"><div class="panel-head"><div><h2>Earning Flow</h2><p>Revenue and expense trend</p></div><div class="chart-legend"><span><b class="line revenue-line"></b>Revenue</span><span><b class="line expense-line"></b>Expenses</span></div></div><div class="chart"><div class="grid-lines"><span></span><span></span><span></span><span></span><span></span></div><svg viewBox="0 0 700 230" preserveAspectRatio="none"><path class="area-a" d="M0 170 C60 195,80 90,145 145 S230 190,290 85 S390 170,450 145 S535 50,590 95 S650 115,700 125 L700 230 L0 230Z"/><path class="area-b" d="M0 190 C60 210,85 150,145 180 S230 205,290 130 S390 190,450 175 S535 110,590 140 S650 155,700 165 L700 230 L0 230Z"/><path class="curve-a" d="M0 170 C60 195,80 90,145 145 S230 190,290 85 S390 170,450 145 S535 50,590 95 S650 115,700 125"/><path class="curve-b" d="M0 190 C60 210,85 150,145 180 S230 205,290 130 S390 190,450 175 S535 110,590 140 S650 155,700 165"/></svg><div class="months"><span>Jan</span><span>Feb</span><span>Mar</span><span>Apr</span><span>May</span><span>Jun</span><span>Jul</span></div></div></article></section>
<section class="bottom-grid"><article class="panel"><div class="panel-head"><div><h2>Recent Transactions</h2><p>Latest entries in your books</p></div><button class="view-btn" data-page="transactions">View all</button></div><div>${db.transactions.slice(-6).reverse().map(t=>`<div class="transaction"><div class="person-icon">LA</div><div class="tx-info"><strong>${esc(t.description)}</strong><small>${t.date}</small></div><div class="tx-amount ${Number(t.credit)>0?"plus":"minus"}">${Number(t.credit)>0?"+":"-"}${money(Number(t.credit)||Number(t.debit))}</div><span class="status ${t.status==="Pending"?"pending":"paid"}">${t.status||"Recorded"}</span></div>`).join("")||'<div class="empty">No transactions yet.</div>'}</div></article>
<article class="panel"><div class="panel-head"><div><h2>Account Information</h2><p>Current business account</p></div><span class="active-badge">● Active</span></div><div class="account-details"><div><span>Account</span><strong>Abba Ishaq Logistics</strong></div><div><span>Account Type</span><strong>Business</strong></div><div><span>Currency</span><strong>ZMW (K)</strong></div><div><span>Transactions</span><strong>${db.transactions.length}</strong></div><div><span>Receivables</span><strong>${money(t.credit)}</strong></div><div><span>Payables</span><strong>${money(t.debit)}</strong></div></div><button class="primary-btn" data-page="accounts">Manage Account</button></article></section>`;
bindPageButtons();
}
function table(rows,cols){if(!rows.length)return '<div class="empty">No records yet.</div>';return `<div class="table-wrap"><table class="data-table"><thead><tr>${cols.map(c=>`<th>${c}</th>`).join("")}</tr></thead><tbody>${rows.map(r=>`<tr>${cols.map(c=>`<td>${esc(r[c]??"")}</td>`).join("")}</tr>`).join("")}</tbody></table></div>`}
function esc(s){return String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function formPanel(title,fields,button){return `<form id="entryForm" class="panel" style="margin-bottom:16px"><h2>${title}</h2><div class="form-grid">${fields}</div><div class="form-actions"><button class="primary-btn" style="width:auto">${button}</button></div></form>`}
function input(id,label,type="text"){return `<div class="field"><label>${label}<input id="${id}" type="${type}" required></label></div>`}
function transactions(){setHeader("Transactions","Record and review debit and credit activity.");$("#pageContent").innerHTML=formPanel("New Transaction",input("date","Date","date")+input("desc","Description")+input("debit","Debit","number")+input("credit","Credit","number")+`<div class="field"><label>Status<select id="status"><option>Paid</option><option>Pending</option></select></label></div>`,"Save Transaction")+`<article class="panel"><h2>Transaction Register</h2>${table(db.transactions,["date","description","debit","credit","status"])}</article>`;$("#entryForm").onsubmit=e=>{e.preventDefault();let d=+$("#debit").value||0,c=+$("#credit").value||0;if(d&&c)return alert("Enter a debit OR a credit for this transaction.");db.transactions.push({date:$("#date").value,description:$("#desc").value,debit:d,credit:c,status:$("#status").value});save();transactions()}}
function accounts(){setHeader("Accounts","Manage customers, suppliers, cash and bank accounts.");$("#pageContent").innerHTML=formPanel("Add Account",input("name","Account Name")+`<div class="field"><label>Account Type<select id="type"><option>Customer</option><option>Supplier</option><option>Cash</option><option>Bank</option></select></label></div>`,"Save Account")+`<article class="panel"><h2>Account Register</h2>${table(db.accounts,["name","type","balance"])}</article>`;$("#entryForm").onsubmit=e=>{e.preventDefault();db.accounts.push({name:$("#name").value,type:$("#type").value,balance:0});save();accounts()}}
function journal(){setHeader("Journal Accounts","JA entries must balance: total debit equals total credit.");$("#pageContent").innerHTML=formPanel("New JA Journal Entry",input("date","Date","date")+input("particulars","Particulars")+input("lf","L.F")+input("debit","Debit","number")+input("credit","Credit","number"),"Save Journal Entry")+`<article class="panel"><h2>Journal Register</h2>${table(db.journal,["date","particulars","lf","debit","credit"])}</article>`;$("#entryForm").onsubmit=e=>{e.preventDefault();let d=+$("#debit").value||0,c=+$("#credit").value||0;if(d!==c)return alert("JA Journal entry must balance. Debit must equal Credit.");db.journal.push({date:$("#date").value,particulars:$("#particulars").value,lf:$("#lf").value,debit:d,credit:c});save();journal()}}
function statements(){setHeader("Statements","Customer and business statements with running balances.");$("#pageContent").innerHTML=formPanel("New Statement Entry",input("date","Date","date")+input("desc","Description")+input("debit","Debit","number")+input("credit","Credit","number"),"Save Statement Entry")+`<article class="panel"><h2>Statement</h2>${table(db.statements,["date","description","debit","credit","balance"])}</article>`;$("#entryForm").onsubmit=e=>{e.preventDefault();let d=+$("#debit").value||0,c=+$("#credit").value||0,prev=db.statements.length?Number(db.statements.at(-1).balance):0;db.statements.push({date:$("#date").value,description:$("#desc").value,debit:d,credit:c,balance:(prev+d-c).toFixed(2)});save();statements()}}
function reports(){let t=totals();setHeader("Reports","Review financial totals and accounting activity.");$("#pageContent").innerHTML=`<section class="stat-grid"><article class="stat-card"><div class="stat-label">Total Debit</div><div class="stat-value">${money(t.debit)}</div></article><article class="stat-card"><div class="stat-label">Total Credit</div><div class="stat-value">${money(t.credit)}</div></article><article class="stat-card"><div class="stat-label">Difference</div><div class="stat-value">${money(t.credit-t.debit)}</div></article><article class="stat-card"><div class="stat-label">Journal Entries</div><div class="stat-value">${db.journal.length}</div></article></section><article class="panel" style="margin-top:18px"><h2>Transaction Report</h2>${table(db.transactions,["date","description","debit","credit","status"])}</article>`}
function staff(){setHeader("Staff Management","Admin-only user and staff management.");$("#pageContent").innerHTML=`<article class="panel"><h2>Users</h2>${table(db.users,["name","username","email","phone","role"])}</article>`}
function settings(){setHeader("Settings","System and business settings.");$("#pageContent").innerHTML='<article class="panel"><h2>Settings</h2><p class="modal-note">Business name: Abba Ishaq Logistics<br>Currency: ZMW (K)<br>System: Logistics Account V4</p></article>'}
function help(){setHeader("Help","Logistics Account V4 guidance.");$("#pageContent").innerHTML='<article class="panel"><h2>Help</h2><p class="modal-note">Use Accounts to create ledgers, Transactions for debit/credit activity, Journal Accounts for balanced JA entries, Statements for running balances, and Reports for summaries.</p></article>'}
const pages={dashboard,transactions,accounts,statements,journal,reports,staff,settings,help};
function load(page){if(page==="staff"&&current.role!=="Admin")return alert("Admin access required.");pages[page]();$$(".nav-item").forEach(x=>x.classList.toggle("active",x.dataset.page===page));$("#sidebar").classList.remove("open")}
function bindPageButtons(){$$("[data-page]").forEach(b=>b.onclick=()=>load(b.dataset.page))}
bindPageButtons();
$("#menuBtn").onclick=()=>$("#sidebar").classList.toggle("open");
$("#logout").onclick=()=>location.reload();
$("#today").textContent=new Date().toLocaleDateString("en-ZM",{weekday:"long",day:"numeric",month:"long",year:"numeric"});
$("#userName").textContent=current.name;$("#userRole").textContent=current.role==="Admin"?"Administrator":"Staff";$("#avatar").textContent=current.name.split(/\s+/).map(x=>x[0]).slice(0,2).join("").toUpperCase();
$("#searchInput").oninput=e=>{const q=e.target.value.toLowerCase();if(!q)return;const found=db.transactions.find(t=>(t.description+" "+t.date).toLowerCase().includes(q));if(found){load("transactions")}};
dashboard();
